[deps]
BFloat16s = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
H5Zblosc = "c8ec2601-a99c-407f-b158-e79c03c2f5f7"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
